version: "3.9"

services:
  postgres:
    container_name: pgql1
    image: postgres:12.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: pgql1
